### ISSUE TITLE
axios.default.request is not defined

### ISSUE THREAD

**Issue by woodser** [woodser/xmr-sample-react#1]
Running the sample app produces this error:

```
Error: Request failed without response: POST https://moneronode.org:18081/json_rpc due to underlying error:
_axios.default.request is not a function
TypeError: _axios.default.request is not a function
    at HttpClient.axiosDigestAuthRequest (http://localhost:3000/static/js/bundle.js:36725:27)
    at http://localhost:3000/static/js/bundle.js:36690:22
    at new Promise (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:36689:16
    at PromiseThrottle._execute (http://localhost:3000/static/js/bundle.js:62736:15)
    at PromiseThrottle.dequeue (http://localhost:3000/static/js/bundle.js:62714:12)
    at http://localhost:3000/static/js/bundle.js:62684:10
    at new Promise (<anonymous>)
    at PromiseThrottle.add (http://localhost:3000/static/js/bundle.js:62676:10)
    at http://localhost:3000/static/js/bundle.js:36688:49
Error: Error: Request failed without response: POST https://moneronode.org:18081/json_rpc due to underlying error:
_axios.default.request is not a function
TypeError: _axios.default.request is not a function
    at HttpClient.axiosDigestAuthRequest (http://localhost:3000/static/js/bundle.js:36725:27)
    at http://localhost:3000/static/js/bundle.js:36690:22
    at new Promise (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:36689:16
    at PromiseThrottle._execute (http://localhost:3000/static/js/bundle.js:62736:15)
    at PromiseThrottle.dequeue (http://localhost:3000/static/js/bundle.js:62714:12)
    at http://localhost:3000/static/js/bundle.js:62684:10
    at new Promise (<anonymous>)
    at PromiseThrottle.add (http://localhost:3000/static/js/bundle.js:62676:10)
    at http://localhost:3000/static/js/bundle.js:36688:49
    at http://localhost:3000/static/js/bundle.js:38119:74
```

Installing axios and making requests directly works as expected.

**Comment by woodser** [comment]
Fixed by https://github.com/woodser/xmr-sample-react/pull/2
